name: Auto Delete Branches

on:
  pull_request:
    types:
      - closed

jobs:
  delete-merged-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        run: |
          branch_name=${{ github.event.pull_request.head.ref }}
          if [[ $branch_name != "main" && $branch_name != "dev" && $branch_name != "prod-support" ]]; then
            git push origin --delete $branch_name
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
